export const TEXTURE_KEYS = {
  BACKGROUND: "background",
  WALL: "wall",
  PLAYER: "player",
  VILLAGER: "villager",
  ZOMBIE: "zombie",
  RANGED: "ranged",
  GHOST: "ghost",
  SKELETON: "skeleton",
  WITCH: "witch",
  BOMBER: "bomber",
  BOSS: "boss",
  PROJECTILE_PLAYER: "projectile_player",
  PROJECTILE_ENEMY: "projectile_enemy",
  SLASH: "slash",
  EXPLOSION: "explosion",
  MEDKIT: "medkit",
  AMMO: "ammo",
  MINE: "mine",
  SHOTGUN: "shotgun",
  GLAIVE: "glaive",
  PISTOL: "pistol",
  BAT: "bat",
};

export const SOUND_KEYS = {
  AMBIENT: "ambient",
  MELODY: "melody",
  PLAYER_ATTACK: "player_attack",
  PLAYER_HIT: "player_hit",
  ENEMY_HIT: "enemy_hit",
  ENEMY_DIE: "enemy_die",
  PICKUP: "pickup",
  MEDKIT: "medkit_use",
  MINE_EXPLODE: "mine_explode",
  LEVEL_UP: "level_up",
  WITCH_SHOOT: "witch_shoot",
};

export const SOUND_DEFAULT_GAINS = {
  [SOUND_KEYS.PLAYER_ATTACK]: 0.55,
  [SOUND_KEYS.PLAYER_HIT]: 0.7,
  [SOUND_KEYS.ENEMY_HIT]: 0.5,
  [SOUND_KEYS.ENEMY_DIE]: 0.6,
  [SOUND_KEYS.PICKUP]: 0.5,
  [SOUND_KEYS.MEDKIT]: 0.55,
  [SOUND_KEYS.MINE_EXPLODE]: 0.75,
  [SOUND_KEYS.LEVEL_UP]: 0.7,
  [SOUND_KEYS.WITCH_SHOOT]: 0.55,
};
