export const TEXTURE_KEYS = {
  BACKGROUND: "background",
  WALL: "wall",
  PLAYER: "player",
  VILLAGER: "villager",
  ZOMBIE: "zombie",
  RANGED: "ranged",
  GHOST: "ghost",
  SKELETON: "skeleton",
  WITCH: "witch",
  BOMBER: "bomber",
  BOSS: "boss",
  BOSS2: "boss2",
  BOSS3: "boss3",
  PROJECTILE_PLAYER: "projectile_player",
  PROJECTILE_ENEMY: "projectile_enemy",
  SLASH: "slash",
  EXPLOSION: "explosion",
  MEDKIT: "medkit",
  AMMO: "ammo",
  MINE_IDLE: "mine_idle",
  MINE_ARMED: "mine_armed",
  BOMB: "bomb",
  SHOTGUN: "shotgun",
  AXE: "axe",
  PISTOL: "pistol",
  BAT: "bat",
  MACHINEGUN: "machinegun",
  PITCHFORK: "pitchfork",
  GRENADE: "grenade",
  SHIELD: "shield",
  CAT: "cat",
};

export const SOUND_KEYS = {
  AMBIENT: "ambient",
  MELODY: "melody",
  PLAYER_ATTACK: "player_attack",
  PLAYER_HIT: "player_hit",
  ENEMY_HIT: "enemy_hit",
  ENEMY_DIE: "enemy_die",
  PICKUP: "pickup",
  MEDKIT: "medkit_use",
  MINE_EXPLODE: "mine_explode",
  LEVEL_UP: "level_up",
  WITCH_SHOOT: "witch_shoot",
  MONSTER_SPAWN: "monster_spawn",
  BOSS2_PHASE: "boss2_phase",
  RESCUE_SPAWN: "rescue_spawn",
  BOSS3_SPAWN: "boss3_spawn",
  WALL_BREAK: "wall_break",
};

export const SOUND_DEFAULT_GAINS = {
  [SOUND_KEYS.PLAYER_ATTACK]: 0.55,
  [SOUND_KEYS.PLAYER_HIT]: 0.7,
  [SOUND_KEYS.ENEMY_HIT]: 0.5,
  [SOUND_KEYS.ENEMY_DIE]: 0.6,
  [SOUND_KEYS.PICKUP]: 0.5,
  [SOUND_KEYS.MEDKIT]: 0.55,
  [SOUND_KEYS.MINE_EXPLODE]: 0.75,
  [SOUND_KEYS.LEVEL_UP]: 0.7,
  [SOUND_KEYS.WITCH_SHOOT]: 0.55,
  [SOUND_KEYS.MONSTER_SPAWN]: 0.45,
  [SOUND_KEYS.BOSS2_PHASE]: 0.7,
  [SOUND_KEYS.RESCUE_SPAWN]: 0.7,
  [SOUND_KEYS.BOSS3_SPAWN]: 0.75,
  [SOUND_KEYS.WALL_BREAK]: 0.65,
};
